default:
  pixels_per_yard: 5

  padding_top: 15
  padding: 0
  background_color: white

  field_color: white
  line_color: black
  end_zone_color: white
  team_name_font_color: white
  touchback_line_color: lightgray
  ball_marker_color: black
  ball_marker_color_on_fly: cyan

  yard_stick:
    length: 5
    head_radius: 2
    head_clearance: 0
    chain_position: 3
    chain_width: 1
    base_color: black
    main_color: black
    number_of_body_lines: 0

  down_marker:
    font_size: 0

real:
  padding_top: 55
  padding: 10
  background_color: gray

  field_color: green
  line_color: white
  end_zone_color: blue
  team_name_font_color: gray
  touchback_line_color: chocolate
  ball_marker_color: cyan
  ball_marker_color_on_fly: yellow

  yard_stick:
    length: 40
    head_radius: 5
    head_clearance: 2
    chain_position: 4
    chain_width: 1
    base_color: black
    main_color: chocolate
    number_of_body_lines: 3

  down_marker:
    font_size: 12
