default:
  pixels_per_yard: 5
  padding_top: 50
  padding: 0

  field_color: white
  line_color: black
  end_zone_color: white
  team_name_font_color: white
  touchback_line_color: lightgray

  yard_stick:
    length: 40
    head_radius: 5
    head_clearance: 2
    chain_position: 4
    chain_width: 1
    base_color: black
    main_color: chocolate
    number_of_body_lines: 3

real:
  padding: 10
  field_color: green
  line_color: white
  end_zone_color: blue
  team_name_font_color: white
  touchback_line_color: chocolate
